[package]
name = "a2_guessing_game"
version = "0.1.0"
authors = ["yangminyu <yangminyu@gosun.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.5.0"

[[bin]]
name = "a2_guessing_game"
path = "main.rs"
