[package]
name = "a4_ownership"
version = "0.1.0"
authors = ["marvinang <marvin_yang@yeah.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "a4_ownership"
path = "main.rs"
