[package]
name = "a3_common_concepts"
version = "0.1.0"
authors = ["yangminyu <yangminyu@gosun.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "a3_common_concepts"
path = "main.rs"
